config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :account do
    resources :projects do
      resources :posts
    end
  end

  namespace :admin do
    resources :projects do
      resources :posts
    end
    resources :posts
  end

  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :project
  belongs_to :user

  validates :content, presence: true
end

app/models/project.rb
class Project < ApplicationRecord

  # 数据栏位校验
  validates :title, presence: true
  validates :description, presence: true

  # 与 user 关系
  belongs_to :user

  # 与 post 关系
  has_many :posts, dependent: :destroy

  # 工程状态
  STATUS = ["communication", "payment", "development", "text", "complete"]
  validates_inclusion_of :status, :in => STATUS

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  # 与 project关系
  has_many :projects, dependent: :destroy

  # 与 post 关系
  has_many :posts, dependent: :destroy

  # email 用户名缩写
  def display_name
    self.email.split("@").first
  end

end

app/controllers/account/posts_controller.rb
class Account::PostsController < ApplicationController
  before_action :authenticate_user!
  layout "account"

  def new
    @project = Project.find(params[:project_id])
    @post = Post.new
  end

  def create
    @project = Project.find(params[:project_id])
    @post = Post.new(post_params)
    @post.project_id = @project.id
    @post.user_id = current_user.id

    if @post.save
      redirect_to account_project_path(@project)
    else
      redirect_to account_project_path(@project)
    end
  end

  private

  def post_params
    params.require(:post).permit(:content, :user_id, :project_id)
  end

end

app/controllers/account/projects_controller.rb
class Account::ProjectsController < ApplicationController
  before_action :authenticate_user!
  layout "account"

  def index
    @projects = Project.where(:user_id => current_user.id).order("created_at DESC")
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user

    if @project.save
      redirect_to account_projects_path
    else
      render :new
    end
  end

  def show
    @project = Project.find(params[:id])
    @post = Post.new
    @posts = @project.posts.order("created_at DESC")
  end

# --------
  private

  def project_params
    params.require(:project).permit(:title, :description, :user_id)
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < AdminController

  def new
    @project = Project.find(params[:project_id])
    @post = Post.new
  end

  def index
    @posts = Post.all.order("created_at DESC")
  end

  def create
    @project = Project.find(params[:project_id])
    @post = Post.new(post_params)
    @post.project_id = @project.id
    @post.user_id = current_user.id

    if @post.save
      redirect_to admin_project_path(@project)
    else
      redirect_to admin_project_path(@project)
    end
  end

  def edit
    @project = Project.find(params[:project_id])
    @post = Post.find(params[:id])
  end

  def update
    @project = Project.find(params[:project_id])
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to admin_project_path(@project)
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:project_id])
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_project_path(@project)
  end

  private

  def post_params
    params.require(:post).permit(:content, :user_id, :project_id)
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < AdminController

  def index
    @projects = Project.all.order("created_at DESC")
  end

  def edit
    @project = Project.find(params[:id])
  end

  def show
    @project = Project.find(params[:id])
    @post = Post.new
    @posts = @project.posts.order("created_at DESC")
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to admin_projects_path
    else
      render :edit
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to admin_projects_path
  end

  # --------
  private

  def project_params
    params.require(:project).permit(:title, :description, :status, :user_id)
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :require_admin!

  layout "admin"

  private

  # 管理员权限判断
  def require_admin!
    if current_user.role != "admin"
      flash[:alert] = "您的权限不足"
      redirect_to root_path
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/account/posts_helper.rb
module Account::PostsHelper
end

app/helpers/account/projects_helper.rb
module Account::ProjectsHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/posts/edit.html.erb
<%= simple_form_for [:admin, @project, @post] do |f| %>
  <div class="form-group">
    <%= f.input :content, as: :ckeditor, ckeditor: { toolbar: 'mini', language: 'zh-CN'}, :label => "任务描述" %>
    <%= f.submit "提交", :class => "button button-actio", :data => { disable_with: "Submiting..." } %>
  </div>
<% end %>

app/views/admin/posts/index.html.erb
<div class="post-index">
  <div class="post-index-box">
    <div class="admin-post-box">
      <% @posts.each do |post| %>
        <%= link_to admin_project_path(post.project) do%>
          <% if post.user.role != "admin" %>
            <div class="admin-customer-post">
              <span><u><strong><%= post.user.display_name %></u> - </strong></span>
              <span><%= post.created_at.strftime("%Y/%m/%d %H:%M:%S") %></span>
              <% if post.project.posts.last.user.role == "admin" %>
                <span class="badge pull-right">已答复</span>
              <% end %>
              <%= simple_format sanitize post.content %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/projects/edit.html.erb
<%= simple_form_for [:admin, @project] do |f| %>
  <div class="form-group">
    <%= f.input :title, :label => "任务标题" %>
    <%= f.input :description, as: :ckeditor, ckeditor: { toolbar: 'mini', language: 'zh-CN'}, :label => "任务描述" %>
    <%= f.input :status, collection: ["communication", "payment", "development", "text", "complete"], :label => "任务状态" %>
    <%= f.submit "提交", :class => "button button-actio", :data => { disable_with: "Submiting..." } %>
  </div>
<% end %>

app/views/admin/projects/index.html.erb
<div class="project-index">

  <% @projects.each do |project| %>

    <%= link_to admin_project_path(project) do %>

      <div class="project-index-box">
        <h2><%= project.title %></h2>

        <span><%= link_to("删除", admin_project_path(project), method: :delete, :class => "button button-pill button-tiny pull-right") %></span>
        <span><%= link_to("编辑", edit_admin_project_path(project), :class => "button button-pill button-tiny pull-right") %></span>
        <span>发布时间:<%= project.created_at.strftime("%Y/%m/%d %H:%M:%S") %></span>
        <hr>
        <%= simple_format sanitize project.description %>
        <hr>

        <!-- 工程进度 -->
        <div class="status-box text-center">
          <!-- 沟通需求 -->
          <% if project.status == "communication"  %>
            <span class="button button-small status-true">沟通需求 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
            <span class="button button-small">确定付款 <i class="fa fa-clock-o fa-lg" aria-hidden="true"></i></span>
            <span class="button button-small">设计开发 <i class="fa fa-clock-o fa-lg" aria-hidden="true"></i></span>
            <span class="button button-small">修改测试 <i class="fa fa-clock-o fa-lg" aria-hidden="true"></i></span>
            <span class="button button-small">完成开发 <i class="fa fa-clock-o fa-lg" aria-hidden="true"></i></span>

          <!-- 确定付款 -->
          <% elsif project.status == "payment"  %>
            <span class="button button-small status-true">沟通需求 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
            <span class="button button-small status-true">确定付款 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
            <span class="button button-small">设计开发 <i class="fa fa-clock-o fa-lg" aria-hidden="true"></i></span>
            <span class="button button-small">修改测试 <i class="fa fa-clock-o fa-lg" aria-hidden="true"></i></span>
            <span class="button button-small">完成开发 <i class="fa fa-clock-o fa-lg" aria-hidden="true"></i></span>

          <!-- 设计开发 -->
          <% elsif project.status == "development"  %>
            <span class="button button-small status-true">沟通需求 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
            <span class="button button-small status-true">确定付款 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
            <span class="button button-small status-true">设计开发 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
            <span class="button button-small">修改测试 <i class="fa fa-clock-o fa-lg" aria-hidden="true"></i></span>
            <span class="button button-small">完成开发 <i class="fa fa-clock-o fa-lg" aria-hidden="true"></i></span>

          <!-- 测试修改 -->
          <% elsif project.status == "text"  %>
            <span class="button button-small status-true">沟通需求 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
            <span class="button button-small status-true">确定付款 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
            <span class="button button-small status-true">设计开发 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
            <span class="button button-small status-true">测试修改 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
            <span class="button button-small">完成开发 <i class="fa fa-clock-o fa-lg" aria-hidden="true"></i></span>

          <!-- 完成开发 -->
          <% elsif project.status == "complete"  %>
            <span class="button button-small status-true">沟通需求 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
            <span class="button button-small status-true">确定付款 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
            <span class="button button-small status-true">设计开发 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
            <span class="button button-small status-true">测试修改 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
            <span class="button button-small status-true">完成开发 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
          <% end %>
        </div>

      </div>

    <% end %>

  <% end %>

</div>

app/views/admin/projects/show.html.erb
<div class="project-index">

  <div class="project-index-box">
    <h2><%= @project.title %></h2>

    <span><%= link_to("删除", admin_project_path(@project), method: :delete, :class => "button button-pill button-tiny pull-right") %></span>
    <span><%= link_to("编辑", edit_admin_project_path(@project), :class => "button button-pill button-tiny pull-right", data: { config: "确定删除吗？" }) %></span>
    <span>发布时间:<%= @project.created_at.strftime("%Y/%m/%d %H:%M:%S") %></span>
    <hr>
    <%= simple_format sanitize @project.description %>
    <hr>

    <!-- 工程进度 -->
    <div class="status-box text-center">
      <!-- 沟通需求 -->
      <% if @project.status == "communication"  %>
        <span class="button button-small status-true">沟通需求 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
        <span class="button button-small">确定付款 <i class="fa fa-clock-o fa-lg" aria-hidden="true"></i></span>
        <span class="button button-small">设计开发 <i class="fa fa-clock-o fa-lg" aria-hidden="true"></i></span>
        <span class="button button-small">修改测试 <i class="fa fa-clock-o fa-lg" aria-hidden="true"></i></span>
        <span class="button button-small">完成开发 <i class="fa fa-clock-o fa-lg" aria-hidden="true"></i></span>

      <!-- 确定付款 -->
      <% elsif @project.status == "payment"  %>
        <span class="button button-small status-true">沟通需求 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
        <span class="button button-small status-true">确定付款 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
        <span class="button button-small">设计开发 <i class="fa fa-clock-o fa-lg" aria-hidden="true"></i></span>
        <span class="button button-small">修改测试 <i class="fa fa-clock-o fa-lg" aria-hidden="true"></i></span>
        <span class="button button-small">完成开发 <i class="fa fa-clock-o fa-lg" aria-hidden="true"></i></span>

      <!-- 设计开发 -->
      <% elsif @project.status == "development"  %>
        <span class="button button-small status-true">沟通需求 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
        <span class="button button-small status-true">确定付款 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
        <span class="button button-small status-true">设计开发 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
        <span class="button button-small">修改测试 <i class="fa fa-clock-o fa-lg" aria-hidden="true"></i></span>
        <span class="button button-small">完成开发 <i class="fa fa-clock-o fa-lg" aria-hidden="true"></i></span>

      <!-- 测试修改 -->
      <% elsif @project.status == "text"  %>
        <span class="button button-small status-true">沟通需求 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
        <span class="button button-small status-true">确定付款 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
        <span class="button button-small status-true">设计开发 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
        <span class="button button-small status-true">测试修改 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
        <span class="button button-small">完成开发 <i class="fa fa-clock-o fa-lg" aria-hidden="true"></i></span>

      <!-- 完成开发 -->
      <% elsif @project.status == "complete"  %>
        <span class="button button-small status-true">沟通需求 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
        <span class="button button-small status-true">确定付款 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
        <span class="button button-small status-true">设计开发 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
        <span class="button button-small status-true">测试修改 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
        <span class="button button-small status-true">完成开发 <i class="fa fa-check-square-o fa-lg" aria-hidden="true"></i></span>
      <% end %>
    </div>


    <!-- new post 输入框 -->
    <div>
      <%= simple_form_for ([:admin, @project, @post]) do |f| %>
        <div class="form-group new-project-form">
          <%= f.input :content, :label => false, :placeholder => "请输入...", :require => true %>
          <%= f.submit "提交", :class => "button button-actio", :data => { disable_with: "Subminting..."} %>
        </div>
      <% end %>
    </div>

    <!-- posts 过程 -->
    <div class="post-box">
      <% @posts.each do |post| %>
        <% if post.user.role != "admin" %>
          <div class="customer-post">
            <span><u><strong><%= post.user.display_name %></u> - </strong></span>
            <span><%= post.created_at.strftime("%Y/%m/%d %H:%M:%S") %></span>
            <span><%= link_to("编辑", edit_admin_project_post_path(@project, post), :class => "button button-pill button-tiny pull-right") %></span>
            <span><%= link_to("删除", admin_project_post_path(@project, post), method: :delete, :class => "button button-pill button-tiny pull-right", data: { config: "确定删除吗？" }) %></span>
            <%= simple_format sanitize post.content %>
          </div>
        <% else %>
          <div class="admin-post">
            <span><%= link_to("编辑", edit_admin_project_post_path(@project, post), :class => "button button-pill button-tiny") %></span>
            <span><%= link_to("删除", admin_project_post_path(@project, post), method: :delete, :class => "button button-pill button-tiny", data: { config: "确定删除吗？" }) %></span>
            <span><%= post.created_at.strftime("%Y/%m/%d %H:%M:%S") %> - </span>
            <span><u><strong><%= post.user.display_name %></u></strong></span>
            <%= simple_format sanitize post.content %>
          </div>
        <% end %>
      <% end %>
    </div>

  </div>

</div>

app/views/common/_footer.html.erb
<footer>
  <div class="container text-center">
    <br>
    <div class="col-sm-7">
      <p>Copyright©2017 南宁简而言之信息科技有限公司</p>
    </div>
    <div class="col-sm-5">
      <p>关于我们  服务协议  合作意向  联系邮箱</p>
    </div>
    <br>
  </div>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">

    <div class="navbar-header">
      <a class="navbar-brand" href="/">简而言之</a>
      <!-- 响应式导航 -->
      <button type="button" class="navbar-toggle"
              data-toggle="collapse"
              data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="navbar-collapse navbar-ex1-collapse collapse navbar-right" aria-expanded="false">
      <ul class="nav navbar-nav navbar-right">


        <% if !current_user %>
          <li><%= link_to("注册", new_user_registration_path) %></li>
          <li><%= link_to("登入", new_user_session_path) %></li>
        <% else %>
          <li class="dropdown navbar-font-size">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.display_name %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% if current_user.role == "admin" %>
                <li><%= link_to("管理员后台", admin_projects_path) %></li>
                <li class="divider"> </li>
              <% end %>
              <li><%= link_to("发布任务", new_account_project_path) %></li>
              <li><%= link_to("进行中任务", account_projects_path) %></li>
              <li><%= link_to("个人中心", account_projects_path) %></li>
              <li class="divider"> </li>
              <li><%= link_to("退出", destroy_user_session_path, method: :delete) %> </li>
            </ul>
          </li>
        <% end %>


      </ul>
    </div>

  </div>
</nav>

app/views/layouts/account.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BaseSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
  </head>

  <body>
    <div class="content">

      <div class="container-fluid">
        <div class="row">
          <%= render "common/navbar" %>
          <div class="container">
            <div class="account-sidebar col-md-3 hidden-sm hidden-xs">

                <%= link_to("发布任务", new_account_project_path, :class => "button button-uppercase button-primary") %>
                <%= link_to("进行中任务", account_projects_path, :class => "button button-uppercase button-primary") %>
                <a href="#" class="button button-uppercase button-primary">个人中心</a>

            </div>
            <div class="account-content col-md-9">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>

    </div>

    <%= render "common/footer" %>

  </body>
</html>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BaseSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
  </head>

  <body>
    <div class="content">

      <div class="container-fluid">
        <div class="row">
          <%= render "common/navbar" %>
          <div class="container">
            <div class="account-sidebar col-md-3 hidden-sm hidden-xs">

                <%= link_to("任务管理", admin_projects_path, :class => "button button-uppercase button-primary") %>
                <%= link_to("客户回复", admin_posts_path, :class => "button button-uppercase button-primary") %>

            </div>
            <div class="account-content col-md-9">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>

    </div>

    <%= render "common/footer" %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BaseSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
  </head>

  <body>
    <div class="content">

      <div class="container-fluid">
        <div class="row">
          <%= render "common/navbar" %>
          <%= yield %>
        </div>

      </div>

    </div>

    <%= render "common/footer" %>

  </body>
</html>